"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=~/.vim/bundles/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  " Let dein manage dein
  " Required:
  call dein#add('~/.vim/bundles/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here:
  call dein#add('Shougo/deoplete.nvim')
  call dein#add('Shougo/vimproc.vim', {'build' : 'make'})
  call dein#add('airblade/vim-gitgutter')
  call dein#add('christoomey/vim-tmux-navigator')
  call dein#add('fatih/vim-go')
  call dein#add('itchyny/vim-cursorword')
  call dein#add('itchyny/vim-gitbranch')
  call dein#add('rafi/vim-tinyline')
  call dein#add('rust-lang/rust.vim')
  call dein#add('scrooloose/nerdtree')
  call dein#add('tmhedberg/SimpylFold')
  call dein#add('tmux-plugins/vim-tmux')
  call dein#add('vim-syntastic/syntastic')

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif

"End dein Scripts-------------------------

"My Own Config----------------------------
colorscheme Tomorrow-Night
let NERDTreeMinimalUI=1
let g:deoplete#enable_at_startup = 1
let g:gitgutter_eager = 1
let g:gitgutter_enabled = 1
let g:gitgutter_realtime = 250
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
map <C-n> :NERDTreeToggle<CR>
map <F8> :call ToggleMouse()<CR>
set encoding=utf-8
set expandtab
set mouse=a
set number
set pastetoggle=<F9>
set shiftwidth=4
set tabstop=4
set termencoding=utf-8

"My Own Function-------------------------
function! ToggleMouse()
    " check if mouse is enabled
    if &mouse == 'a'
        " disable mouse
        set mouse=
    else
        " enable mouse everywhere
        set mouse=a
    endif
endfunc
